### PR TITLE
Just comms

### PR DESCRIPTION
**Pull request by naterush**
This PR is @blois's code from the Comms n Widgets PR (#6), with all the widget code removed. 

I broke this out for my own learning (huge!), but also so the Comm code is easier to manage/review. @blois, thoughts on getting this merged before adding in widget complexity?

A few open questions in my mind:
1. Do we want to move forward with this `Comm` interface (notably, missing the onMsg ). The idea here (I guess) is that this Comm interface will be totally cross-platform compatible. Seems legit to me, but on the other hand might be confusing to JupyterLab-only folks. Since I'm new to these sort of tradeoffs, would love to hear more behind the thought process here!
2. How are these notebooks for testing generally? I originally missed the testing notebook and implement different ones, but the one from the Widgets n Comms PR is great. Ideally, I think this notebook becomes the acceptance criteria for a platform being spec compliant for rich output!

Anything else I missed? I'm new to all this code, just doing my best to help push things forward - so all feedback massively appreciated :)

### CODE REVIEW

**Comment by blois** [comment]
This is awesome- excited to see more progress! Breaking it up is great as well- I had them combined just because I wanted to show some viability of the primitives.

For `onMsg` - is this referring to the `messages: AsyncIterable<ICommMessage>` alternate API? I'm open to adding onMsg instead- I think async iterables have a lot of power, but they are still fairly new and the code to support them is non-trivial.

I think there needs to be a close handler as well? Some alternatives:

```typescript
// Follows the pattern of the IteratorResult type:
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterator_protocol
// Returns a function which when called will remove the handler.
onMessage(callback: (data: {message: ICommMessage, done: boolean}) => void): () => void;
```

Or an expanded version:
```typescript
// Returns a function which when called will remove the handler.
onMessage(callback: (message: ICommMessage) => void): () => void;
onClose(callback: () => void): () => void;
```

For testing, notebooks are a nice portable mechanism for a variety of clients. Would be nice to try to cram as much into them as possible but  it's going to be tricky to have perfect coverage. Would be good to see how much mileage can be gotten out of them.

**Comment by naterush** [comment]
Thanks for the feedback! Yeah, I like the messages interface -- but agree that onMessage and onClose seem like a good v1 for the interface simply for complexity reasons. 

So my next steps:
1. Implement `onMessage` and `onClose`
2. Test them in the notebook (woo)

The other big thing to figure out is that [the output doesn't wait for previous outputs to finish rendering](https://github.com/jupyterlab/richoutput-js/pull/6#issuecomment-1548247314). I don't think we need to fix in this PR, but seems like a good next target to fix up after getting this merged. There might be a very simple solution, but I'm new to all that code. Let me know if you have any hunches I can follow up on! Otherwise, I'll dig in more in the future.

Thanks again :)

**Comment by naterush** [comment]
Ok, the `onMessage` and `onClose` interfaces should be up and running. Tests included in the notebook as well. Let me know if there's more you want me to clean or test, but I think the Comms part of the PR can be wrapped up soon! @blois pinging you so you see the notifications.

**Comment by naterush** [comment]
@blois absolutely no rush, but if you get the chance to review this sometime it would be greatly appreciated! Once this is good to go, I'll move on to some experiments with `sharedState` :)

**Comment by blois** [comment]
The changes look good to me, I'm not too familiar with this build system so am not sure what the error is on the build. Patching this in locally and it seems to work well.

**Pull request closed without merging**
